/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package buontyhunter;
import java.awt.Dimension;
import javax.swing.JFrame;

public class App {
    private static final String APPLICATION_TITLE = "Buonty Hunter v1.0";
    private static final int screenWidth = 600;
    private static final int screenHeight = 400;

    public static void main(String[] args) {
        JFrame frame = new JFrame(APPLICATION_TITLE);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLocationRelativeTo(null);

        Dimension screenDimension = new Dimension(screenWidth, screenHeight);

        

        frame.setPreferredSize(screenDimension);
        frame.setSize(screenDimension);
        frame.setLocationRelativeTo(null);
        frame.setResizable(true);
        frame.setVisible(true);
    }
}
