/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package buontyhunter;

import buontyhunter.Core.GameEngine;

public class App {

    public static void main(String[] args) {
        GameEngine engine = new GameEngine();
        engine.gameRun();
    }
}
