/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package buontyhunter;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import buontyhunter.common.*;
import buontyhunter.core.*;
import buontyhunter.graphics.PlayerGraphicsComponent;
import buontyhunter.input.KeyBoardController;
import buontyhunter.input.PlayerInputController;
import buontyhunter.model.*;

class AppTest {

}
